=== Thavis/hydra/doc/01_documentation/meta/schema.xsd
<xsd:schema xmlns="http://tnt-code.com/schema/hydra/doc"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            targetNamespace="http://tnt-code.com/schema/hydra/doc"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="chapter">
        <xsd:complexType>
            <xsd:complexContent>
                <xsd:extension base="contentType">
                    <xsd:sequence>
                        <xsd:element name="summary" type="contentType"/>
                    </xsd:sequence>
                    <xsd:attribute name="title"/>
                </xsd:extension>
            </xsd:complexContent>
        </xsd:complexType>
    </xsd:element>


    <xsd:element name="list">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="li" minOccurs="1" maxOccurs="unbounded" type="contentType"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="dict">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="di" minOccurs="1" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:complexContent>
                            <xsd:extension base="contentType">
                                <xsd:attribute name="name" use="required"/>
                            </xsd:extension>
                        </xsd:complexContent>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="contentType" mixed="true">
        <xsd:sequence>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element ref="list"/>
                <xsd:element ref="dict"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Thavis/hydra/doc/01_documentation/01_requiements.xml
<chapter title="Requirements"
        xmlns="http://tnt-code.com/schema/hydra/doc"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://tnt-code.com/schema/hydra/doc meta/schema.xsd">

    <summary>Main requirements and targets assumed for language definitions.</summary>

    List of main requirements:
    <list>
        <li>Language must support:
            <list>
                <li>grammar libraries</li>
                <li>instruction overrides</li>
                <li>instruction extensions</li>
                <li>language injections</li>
                <li>language embedding</li>
            </list>
        </li>
    </list>
</chapter>

=== Thavis/hydra/doc/01_documentation/02_definitions.xml
<chapter title="Definitions"
        xmlns="http://tnt-code.com/schema/hydra/doc"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://tnt-code.com/schema/hydra/doc meta/schema.xsd">

    <summary>List of used definitions with explanations.</summary>

    <dict>
        <di name="Token">Atomic chain of characters representing single parsing unit.</di>
        <di name="Grammar">Set of instructions defining rules of constructing and parsing source.</di>
        <di name="Grammar library">Artifact representing reusable and redefinable set of grammar instructions.</di>
        <di name="Instruction override">Redefinition of grammar instruction within specified scope under original name.</di>
        <di name="Instruction extension">Constructing new grammar instruction by extending existing definition.</di>
        <di name="Language injections">Wrapping different grammar withing specified elements of defined language. For example argument of every java.sql.Statement.executeQuery call can be resolved as SQL statements.</di>
        <di name="Language embedding">Including different grammar as native part of specified language. For example including native XML as part of source code.</di>
    </dict>
</chapter>
